#!/usr/bin/env python3
"""Generate the browser data module from Nexluna's canonical units JSON."""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "data" / "units.json"
OUTPUT = ROOT / "assets" / "js" / "units.generated.js"
EXPECTED_CATEGORIES = {
    "length", "weight", "area", "volume", "temperature", "data", "speed",
    "time", "pressure", "energy", "power", "angle", "fuel", "frequency",
}


def fail(message: str) -> None:
    raise ValueError(message)


def validate(data: object) -> dict:
    if not isinstance(data, dict):
        fail("canonical units data must be an object")
    keys = set(data)
    missing = EXPECTED_CATEGORIES - keys
    extra = keys - EXPECTED_CATEGORIES
    if missing:
        fail(f"missing categories: {', '.join(sorted(missing))}")
    if extra:
        fail(f"unexpected categories: {', '.join(sorted(extra))}")

    for category, definition in data.items():
        if not isinstance(definition, dict):
            fail(f"{category}: definition must be an object")
        for required in ("icon", "label", "title", "units", "provenance", "unit_provenance"):
            if required not in definition:
                fail(f"{category}: missing {required}")
        provenance = definition["provenance"]
        if not isinstance(provenance, dict):
            fail(f"{category}: provenance must be an object")
        for required in ("schema_version", "system", "region", "source", "reviewed", "notes"):
            if not isinstance(provenance.get(required), str) or not provenance[required]:
                fail(f"{category}: provenance missing {required}")
        units = definition["units"]
        if not isinstance(units, list) or not units:
            fail(f"{category}: units must be a non-empty list")
        ids = []
        for unit in units:
            if not isinstance(unit, list) or len(unit) != 2 or not all(isinstance(x, str) and x for x in unit):
                fail(f"{category}: each unit must be [id, label]")
            ids.append(unit[0])
        if len(ids) != len(set(ids)):
            fail(f"{category}: duplicate unit id")
        unit_provenance = definition["unit_provenance"]
        if not isinstance(unit_provenance, dict) or set(unit_provenance) != set(ids):
            fail(f"{category}: unit_provenance keys must match unit ids")
        for unit_id in ids:
            record = unit_provenance[unit_id]
            if not isinstance(record, dict):
                fail(f"{category}/{unit_id}: provenance must be an object")
            for required in ("system", "region", "definition", "source", "reviewed"):
                if not isinstance(record.get(required), str) or not record[required]:
                    fail(f"{category}/{unit_id}: provenance missing {required}")
        if definition.get("temp"):
            if set(ids) != {"C", "F", "K"}:
                fail("temperature: expected C, F, K")
        elif definition.get("special") == "fuel":
            if set(ids) != {"kml", "l100", "mpg", "mpgUK"}:
                fail("fuel: expected kml, l100, mpg, mpgUK")
        else:
            base = definition.get("base")
            if not isinstance(base, dict) or set(base) != set(ids):
                fail(f"{category}: base keys must match unit ids")
            if not all(isinstance(value, (int, float)) and value > 0 for value in base.values()):
                fail(f"{category}: base factors must be positive numbers")
    return data


def render(data: dict) -> str:
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"), allow_nan=False)
    return (
        "/* Generated from data/units.json. Do not edit this file directly. */\n"
        "(function (root) {\n"
        "  'use strict';\n"
        f"  root.NexlunaUnits = {payload};\n"
        "})(typeof window !== 'undefined' ? window : globalThis);\n"
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="validate and compare without writing")
    args = parser.parse_args()
    try:
        data = validate(json.loads(SOURCE.read_text(encoding="utf-8")))
        rendered = render(data)
        if args.check:
            if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != rendered:
                print("generated units file is stale; run: python3 scripts/generate_units.py --write", file=sys.stderr)
                return 1
            print(f"OK: {len(data)} categories validated and generated file is current")
            return 0
        OUTPUT.write_text(rendered, encoding="utf-8")
        print(f"Wrote {len(data)} categories to {OUTPUT.relative_to(ROOT)}")
        return 0
    except (OSError, json.JSONDecodeError, ValueError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
